# Generated by Django 4.0.4 on 2022-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contact_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
